# Generated by Django 3.1.5 on 2021-08-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decathlon_Stores',
            fields=[
                ('StoreID', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=100)),
                ('StoreCity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Decathlon_Products',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductSport', models.CharField(max_length=100)),
                ('ProductLevel', models.CharField(max_length=100)),
                ('ProductDescription', models.CharField(max_length=100)),
                ('AssociatedStores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.decathlon_stores')),
            ],
        ),
    ]
