# Generated by Django 3.1.5 on 2021-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decathlon_products',
            name='AssociatedStores',
        ),
        migrations.AddField(
            model_name='decathlon_products',
            name='AssociatedStores',
            field=models.ManyToManyField(to='api.Decathlon_Stores'),
        ),
    ]
