# Generated by Django 3.1.5 on 2021-09-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210813_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decathlon_products',
            name='ProductDescription',
            field=models.TextField(),
        ),
    ]
